version: 1
root:
    level: DEBUG
    handlers: [error]
formatters:
    simpleFormatter:
        format: "%(asctime)s\t%(levelname)s\t%(threadName)s\t%(message)s"
#        datefmt: '%Y-%m-%d %H:%M:%S.%f'

handlers:
    response:
        class: logging.StreamHandler
        formatter: simpleFormatter
        level: DEBUG
        stream: ext://sys.stdout
    error:
        class : logging.StreamHandler
        formatter: simpleFormatter
        level: DEBUG
        stream: ext://sys.stderr

loggers:
    drett_server:
        propagate: false
        level: DEBUG
        handlers: [error]
    drett_client:
        propagate: false
        level: DEBUG
        handlers: [response]
