version: 1
root:
    level: DEBUG
    handlers: [stderr, syslog]
formatters:
    simpleFormatter:
        format: "%(asctime)s\t%(levelname)s\t%(threadName)s\t%(message)s"

handlers:
    stdout:
        class: logging.StreamHandler
        formatter: simpleFormatter
        level: DEBUG
        stream: ext://sys.stdout
    stderr:
        class : logging.StreamHandler
        formatter: simpleFormatter
        level: DEBUG
        stream: ext://sys.stderr
    syslog:
            level: INFO
            formatter: simpleFormatter
            class: logging.handlers.SysLogHandler
            address: /dev/log

loggers:
    drett_server:
        propagate: false
        level: DEBUG
        handlers: [stdout, syslog]
